# Arrays

In [1]:
import numpy

def arrays(arr):
    fl=numpy.array(arr,float)
    return (fl[::-1])

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6
[6. 5. 4. 3. 2. 1.]


# Shape and Reshape

In [2]:
import numpy
arr = input().strip().split(' ')
a=numpy.array(arr,int)
print(a.reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose and Flatten

In [3]:
import numpy
n , m = input().split();
a = []
for i in range(int(n)):
    my_array = input().split()
    a.append(my_array)
    
lis1 = numpy.array(a,int)
print(numpy.transpose(lis1))
print(lis1.flatten())

2 2
13 12
3 6
[[13  3]
 [12  6]]
[13 12  3  6]


# Concatenate

In [1]:
import numpy
n , m , p = input().split();
pn = []
for i in range(int(n)):
    my_array = input().split()
    pn.append(my_array)
    arr1=numpy.array(pn,int)
pm = []
for i in range(int(m)):
    my_array = input().split()
    pm.append(my_array)
    arr2=numpy.array(pm,int)
print(numpy.concatenate((arr1, arr2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Zeros and Ones

In [2]:
import numpy
a=list(map(int, input().split()))
print(numpy.zeros(a, int))
print(numpy.ones(a,int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Eye and Identity

In [4]:
import numpy
numpy.set_printoptions(legacy='1.13')
a=input().split(" ")
print(numpy.eye(int(a[0]), int(a[1])))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Array Mathematics

In [5]:
import numpy
n , m = input().split();
a = []
b = []

for i in range(int(n)):
    my_array = input().split()
    a.append(my_array)
    arr1=numpy.array(a,int)
    
for i in range(int(n)):
    my_array = input().split()
    b.append(my_array)
    arr2=numpy.array(b,int)
    
print(numpy.add(arr1,arr2))
print(numpy.subtract(arr1,arr2))
print(numpy.multiply(arr1,arr2))
print(arr1//arr2)
print(numpy.mod(arr1,arr2))
print(numpy.power(arr1,arr2))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# floor, ceil, rint

In [6]:
import numpy
numpy.set_printoptions(legacy='1.13')
elem=input().split(" ")
A=numpy.array(elem,float)
print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Sum and Prod

In [7]:
import numpy
n,m=map(int,input().split())
arr=[]
for i in range(n):
    elem=input().split()
    arr.append(elem)
    A=numpy.array(arr,int)
s=numpy.sum(A,axis=0)
print(numpy.prod(s))

2 2
2 3
4 7
60


# Min and Max

In [8]:
import numpy
n,m=map(int,input().split())
arr=[]
for i in range(n):
    elem=input().split()
    arr.append(elem)
    A=numpy.array(arr,int)
s=numpy.min(A,axis=1)
print(numpy.max(s))

4 2
2 5
3 7
1 3
4 0
3


# Mean, Var and Std

In [9]:
import numpy
n,m=map(int,input().split())
arr=[]
for i in range(n):
    elem=input().split()
    arr.append(elem)
    A=numpy.array(arr,int)
print(numpy.mean(A,axis=1))
print(numpy.var(A,axis=0))
print(numpy.std(A))

2 2 
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Linear Algebra

In [10]:
import numpy
n = int(input()) 
A = numpy.array([input().split() for i in range(n)], float) 
print(round(numpy.linalg.det(A),2))

2
1.1 1.1
1.1 1.1
0.0


# Dot and Cross

In [11]:
import numpy
n=int(input())
a=[]
b=[]
for i in range(n):
    elem=input().split()
    a.append(elem)
    arr1 = numpy.array(a,int)
    
for i in range(n):
    elem=input().split()
    b.append(elem)
    arr2 = numpy.array(b,int)
    
print(numpy.dot(arr1,arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Inner and Outer

In [12]:
import numpy
elem_A=input().split()
A=numpy.array(elem_A,int)
elem_B=input().split()
B=numpy.array(elem_B,int)
print(numpy.inner(A,B))
print(numpy.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


# Polynomials

In [13]:
import numpy
l1 = list(map(float,input().split()))
x = int(input())
print(numpy.polyval(l1,x))

1.1 2 3
0
3.0
